install.packages("jsonlite")
library("jsonlite")
system('wget -O nfl.json "http://api.fantasy.nfl.com/v1/players/stats?statType=seasonStats&season=2010&week=1&format=json"')
mydf <- fromJSON("nfl.json")
class(mydf$players)
print(head(mydf$players,10))
